sudo: false

dist: xenial

language: c

os:
  - linux

python:
  - "3.7"

compiler:
  - gcc

addons:
  apt:
    packages:
      - gcc-multilib

git:
  # we want to do this ourselves
  submodules: false

script:
  - make
