EXTRA_CFLAGS := -I$(TOPDIR)/fs/grub -I$(TOPDIR)/fs/fatx -I$(TOPDIR)/lib/crypt -I$(TOPDIR)/drivers/flash -I$(TOPDIR)/drivers/cpu -I$(TOPDIR)/drivers/ide

O_TARGET := BootStartBios.o BootStartup.o BootResetAction.o

include $(TOPDIR)/Rules.make
