
EXTRA_CFLAGS := -I$(TOPDIR)/jpeg-6b/ -DNO_GETENV

O_TARGET := jdapimin.o jdapistd.o jdtrans.o jdatasrc.o jdmaster.o \
	jdinput.o jdmarker.o jdhuff.o jdphuff.o jdmainct.o jdcoefct.o \
	jdpostct.o jddctmgr.o jidctfst.o jidctflt.o jidctint.o jidctred.o \
	jdsample.o jdcolor.o jquant1.o jquant2.o jdmerge.o jmemnobs.o \
	jmemmgr.o jcomapi.o jutils.o jerror.o

include $(TOPDIR)/Rules.make
