EXTRA_CFLAGS := -I$(TOPDIR)/menu/textmenu -I$(TOPDIR)/fs/grub -I$(TOPDIR)/fs/fatx -I$(TOPDIR)/lib/crypt
O_TARGET := MenuActions.o VideoMenuActions.o ResetMenuActions.o FlashMenuActions.o HddMenuActions.o
include $(TOPDIR)/Rules.make
