EXTRA_CFLAGS := -I$(TOPDIR)/fs/grub -I$(TOPDIR)/menu/actions -I$(TOPDIR)/lib/crypt 
O_TARGET := TextMenu.o TextMenuInit.o VideoMenuInit.o ResetMenuInit.o FlashMenuInit.o HddMenuInit.o
include $(TOPDIR)/Rules.make
